/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbo;

/**
 *
 * @author SaIN
 */
public class form_mata_kuliah extends javax.swing.JFrame {

    /**
     * Creates new form form_mata_kuliah
     */
    public form_mata_kuliah() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        tentang_pembuat = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        data_mahasiswa = new javax.swing.JPanel();
        icon1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        data_mata_kuliah = new javax.swing.JPanel();
        icon2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        data_nilai = new javax.swing.JPanel();
        icon3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Simulasi_nilai_akhir1 = new javax.swing.JPanel();
        icon5 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        Simulasi_nilai_akhir = new javax.swing.JPanel();
        icon4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_batal = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btn_hapus = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btn_ubah = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btn_simpan = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btn_keluar = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        btn_tambah = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setPreferredSize(new java.awt.Dimension(900, 500));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebar.setBackground(new java.awt.Color(65, 83, 128));
        sidebar.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tentang_pembuat.setBackground(new java.awt.Color(65, 83, 128));
        tentang_pembuat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tentang_pembuat.setPreferredSize(new java.awt.Dimension(175, 43));
        tentang_pembuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tentang_pembuatMouseClicked(evt);
            }
        });

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/picture/people_20px.png"))); // NOI18N

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tentang Pembuat");

        javax.swing.GroupLayout tentang_pembuatLayout = new javax.swing.GroupLayout(tentang_pembuat);
        tentang_pembuat.setLayout(tentang_pembuatLayout);
        tentang_pembuatLayout.setHorizontalGroup(
            tentang_pembuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tentang_pembuatLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(icon)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        tentang_pembuatLayout.setVerticalGroup(
            tentang_pembuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tentang_pembuatLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(tentang_pembuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(icon)
                    .addComponent(jLabel3))
                .addGap(16, 16, 16))
        );

        sidebar.add(tentang_pembuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 390, 204, 36));

        data_mahasiswa.setBackground(new java.awt.Color(65, 83, 128));
        data_mahasiswa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        data_mahasiswa.setPreferredSize(new java.awt.Dimension(175, 43));
        data_mahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                data_mahasiswaMouseClicked(evt);
            }
        });

        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/picture/student_male_20px.png"))); // NOI18N

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Data Mahasiswa");

        javax.swing.GroupLayout data_mahasiswaLayout = new javax.swing.GroupLayout(data_mahasiswa);
        data_mahasiswa.setLayout(data_mahasiswaLayout);
        data_mahasiswaLayout.setHorizontalGroup(
            data_mahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data_mahasiswaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(icon1)
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        data_mahasiswaLayout.setVerticalGroup(
            data_mahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, data_mahasiswaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(data_mahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon1)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        sidebar.add(data_mahasiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, 225, 36));

        data_mata_kuliah.setBackground(new java.awt.Color(65, 83, 128));
        data_mata_kuliah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        data_mata_kuliah.setPreferredSize(new java.awt.Dimension(175, 43));
        data_mata_kuliah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                data_mata_kuliahMouseClicked(evt);
            }
        });

        icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/picture/open_book_20px.png"))); // NOI18N

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Data Mata Kuliah");

        javax.swing.GroupLayout data_mata_kuliahLayout = new javax.swing.GroupLayout(data_mata_kuliah);
        data_mata_kuliah.setLayout(data_mata_kuliahLayout);
        data_mata_kuliahLayout.setHorizontalGroup(
            data_mata_kuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data_mata_kuliahLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(icon2)
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        data_mata_kuliahLayout.setVerticalGroup(
            data_mata_kuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, data_mata_kuliahLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(data_mata_kuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon2)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        sidebar.add(data_mata_kuliah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 97, 225, 36));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("APLIKASI KEMAHASISWAAN");
        sidebar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, -1, -1));

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 30));
        sidebar.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 225, 10));

        data_nilai.setBackground(new java.awt.Color(65, 83, 128));
        data_nilai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        data_nilai.setPreferredSize(new java.awt.Dimension(175, 43));
        data_nilai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                data_nilaiMouseClicked(evt);
            }
        });

        icon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/picture/clipboard_list_20px.png"))); // NOI18N

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Data Nilai");

        javax.swing.GroupLayout data_nilaiLayout = new javax.swing.GroupLayout(data_nilai);
        data_nilai.setLayout(data_nilaiLayout);
        data_nilaiLayout.setHorizontalGroup(
            data_nilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data_nilaiLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(icon3)
                .addGap(29, 29, 29)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        data_nilaiLayout.setVerticalGroup(
            data_nilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, data_nilaiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(data_nilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon3)
                    .addComponent(jLabel7))
                .addContainerGap())
        );

        sidebar.add(data_nilai, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 139, 235, 36));

        Simulasi_nilai_akhir1.setBackground(new java.awt.Color(65, 83, 128));
        Simulasi_nilai_akhir1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Simulasi_nilai_akhir1.setPreferredSize(new java.awt.Dimension(175, 43));
        Simulasi_nilai_akhir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Simulasi_nilai_akhir1MouseClicked(evt);
            }
        });

        icon5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/picture/task_23px.png"))); // NOI18N

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Simulasi Kasus");

        javax.swing.GroupLayout Simulasi_nilai_akhir1Layout = new javax.swing.GroupLayout(Simulasi_nilai_akhir1);
        Simulasi_nilai_akhir1.setLayout(Simulasi_nilai_akhir1Layout);
        Simulasi_nilai_akhir1Layout.setHorizontalGroup(
            Simulasi_nilai_akhir1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Simulasi_nilai_akhir1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(icon5)
                .addGap(26, 26, 26)
                .addComponent(jLabel24)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        Simulasi_nilai_akhir1Layout.setVerticalGroup(
            Simulasi_nilai_akhir1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Simulasi_nilai_akhir1Layout.createSequentialGroup()
                .addGroup(Simulasi_nilai_akhir1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(icon5))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        sidebar.add(Simulasi_nilai_akhir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 235, 36));

        Simulasi_nilai_akhir.setBackground(new java.awt.Color(65, 83, 128));
        Simulasi_nilai_akhir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Simulasi_nilai_akhir.setPreferredSize(new java.awt.Dimension(175, 43));
        Simulasi_nilai_akhir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Simulasi_nilai_akhirMouseClicked(evt);
            }
        });

        icon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/picture/todo_list_20px.png"))); // NOI18N

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Simulasi Nilai Akhir");

        javax.swing.GroupLayout Simulasi_nilai_akhirLayout = new javax.swing.GroupLayout(Simulasi_nilai_akhir);
        Simulasi_nilai_akhir.setLayout(Simulasi_nilai_akhirLayout);
        Simulasi_nilai_akhirLayout.setHorizontalGroup(
            Simulasi_nilai_akhirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Simulasi_nilai_akhirLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(icon4)
                .addGap(29, 29, 29)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Simulasi_nilai_akhirLayout.setVerticalGroup(
            Simulasi_nilai_akhirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Simulasi_nilai_akhirLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Simulasi_nilai_akhirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon4)
                    .addComponent(jLabel8))
                .addContainerGap())
        );

        sidebar.add(Simulasi_nilai_akhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 181, 235, 36));

        background.add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(65, 83, 128));
        jLabel2.setText("Masukkan Data");
        background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, 20));

        jSeparator2.setForeground(new java.awt.Color(65, 83, 128));
        background.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 580, 10));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(65, 83, 128));
        jLabel9.setText("Pencarian Data Mata Kuliah");
        background.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, 20));
        background.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 220, -1));

        jSeparator3.setForeground(new java.awt.Color(65, 83, 128));
        background.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 580, 10));

        jPanel3.setBackground(new java.awt.Color(56, 148, 161));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM MATA KULIAH");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        background.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 650, 50));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(65, 83, 128));
        jLabel10.setText("Nama M.K");
        background.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, -1, 20));
        background.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, 170, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(65, 83, 128));
        jLabel11.setText("Nomor M.K");
        background.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, 20));
        background.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 180, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 580, 170));

        btn_batal.setBackground(new java.awt.Color(255, 255, 255));
        btn_batal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_batal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_batal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Batal");
        btn_batal.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/picture/file_delete_20px.png"))); // NOI18N
        btn_batal.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        background.add(btn_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, 80, 40));

        btn_hapus.setBackground(new java.awt.Color(255, 255, 255));
        btn_hapus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_hapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_hapus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Hapus");
        btn_hapus.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/picture/delete_20px.png"))); // NOI18N
        btn_hapus.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        background.add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 90, 40));

        btn_ubah.setBackground(new java.awt.Color(255, 255, 255));
        btn_ubah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_ubah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ubah.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Simpan");
        btn_ubah.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/picture/add_file_20px.png"))); // NOI18N
        btn_ubah.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        background.add(btn_ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, 90, 40));

        btn_simpan.setBackground(new java.awt.Color(255, 255, 255));
        btn_simpan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_simpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_simpan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Ubah");
        btn_simpan.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/picture/edit_20px.png"))); // NOI18N
        btn_simpan.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        background.add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 80, 40));

        btn_keluar.setBackground(new java.awt.Color(255, 255, 255));
        btn_keluar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_keluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_keluar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setText("Keluar");
        btn_keluar.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/picture/cancel_20px.png"))); // NOI18N
        btn_keluar.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        background.add(btn_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 370, 90, 40));

        btn_tambah.setBackground(new java.awt.Color(255, 255, 255));
        btn_tambah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_tambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_tambah.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Tambah");
        btn_tambah.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/picture/add_20px.png"))); // NOI18N
        btn_tambah.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        background.add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 886, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tentang_pembuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tentang_pembuatMouseClicked
        // TODO add your handling code here:
//        text_ubah.setText("Ini Tentang Pembuat");
    }//GEN-LAST:event_tentang_pembuatMouseClicked

    private void data_mahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_data_mahasiswaMouseClicked
        // TODO add your handling code here:
//        text_ubah.setText("Ini Data Mahasiswa");
    }//GEN-LAST:event_data_mahasiswaMouseClicked

    private void data_mata_kuliahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_data_mata_kuliahMouseClicked
        // TODO add your handling code here:
//        text_ubah.setText("Ini Data Mata Kuliah");
    }//GEN-LAST:event_data_mata_kuliahMouseClicked

    private void data_nilaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_data_nilaiMouseClicked
        // TODO add your handling code here:
//        text_ubah.setText("Ini Data Nilai");
    }//GEN-LAST:event_data_nilaiMouseClicked

    private void Simulasi_nilai_akhirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Simulasi_nilai_akhirMouseClicked
        // TODO add your handling code here:
//        text_ubah.setText("Ini Simulasi Nilai Akhir");
    }//GEN-LAST:event_Simulasi_nilai_akhirMouseClicked

    private void Simulasi_nilai_akhir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Simulasi_nilai_akhir1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Simulasi_nilai_akhir1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_mata_kuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_mata_kuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_mata_kuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_mata_kuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_mata_kuliah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Simulasi_nilai_akhir;
    private javax.swing.JPanel Simulasi_nilai_akhir1;
    private javax.swing.JPanel background;
    private javax.swing.JPanel btn_batal;
    private javax.swing.JPanel btn_hapus;
    private javax.swing.JPanel btn_keluar;
    private javax.swing.JPanel btn_simpan;
    private javax.swing.JPanel btn_tambah;
    private javax.swing.JPanel btn_ubah;
    private javax.swing.JPanel data_mahasiswa;
    private javax.swing.JPanel data_mata_kuliah;
    private javax.swing.JPanel data_nilai;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel icon2;
    private javax.swing.JLabel icon3;
    private javax.swing.JLabel icon4;
    private javax.swing.JLabel icon5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel sidebar;
    private javax.swing.JPanel tentang_pembuat;
    // End of variables declaration//GEN-END:variables
}
